### ISSUE TITLE
Don't show a hidden container when opening new links in that container

### ISSUE THREAD

**Issue by Keith94** [mozilla/testpilot-containers#618] opened 2017-06-22 04:29 UTC
After a container is hidden manually, I'd prefer if opening new links in that container would not load that new tab (and existing tabs) automatically, instead only load them when 'show this container' is selected manually.

**Comment by jonathanKingston** [comment] 2017-06-22 10:55
I'm pretty sure this is a duplicate. This was intended behaviour that we knew about, but we said we would review.

@kjozwiak or @groovecoder I couldn't find the bug for this, do you know if we had one?

**Comment by SoftVision-CiprianMuresan** [comment] 2017-06-22 11:57
@jonathanKingston, is #290 what you were looking for?

**Comment by jonathanKingston** [comment] 2017-06-22 12:55
@SoftVision-CiprianMuresan yes thanks.

Duplicate of: #348 and #290 

#348 is the currently open issue left to discuss this.

**Closed by jonathanKingston** 2017-06-22 12:55 UTC
Labels: duplicate, enhancement
