### ISSUE TITLE
containers disappeared from nightly update 57.0a1 (2017-08-15) (64 bits)

### ISSUE THREAD

**Issue by guydunigo** [mozilla/testpilot-containers#733] opened 2017-08-16 08:33 UTC
It is still listed under the extensions page but I can't find the icon to add it to the add-ons bar nor can use I the right-click (always open in this container) option.

**Comment by ArchangeGabriel** [comment] 2017-08-16 08:43
See #725. This should be fixed with update to 3.1 apparently.

**Comment by Caemor** [comment] 2017-08-16 10:58
When will the version 3.1 be released on the official site?

Also the signed xpi seems to be broke when i tried to update manually (at least ff nightly tells me that for it, see: https://github.com/mozilla/testpilot-containers/releases/tag/3.1.0 )

**Comment by jonathanKingston** [comment] 2017-08-16 11:10
@Caemor did you try setting "xpinstall.signatures.dev-root" to true in about config when installing the staged signed or xpi signing to false and legacy extensions to enabled when using the unsigned?

**Comment by jonathanKingston** [comment] 2017-08-16 11:10
Also gonna close this out as it's a duplicate of #725

**Comment by jonathanKingston** [comment] 2017-08-16 11:11
> When will the version 3.1 be released on the official site?

Should be today.

**Closed by jonathanKingston** 2017-08-16 11:10 UTC
Labels: duplicate

**Comment by Caemor** [comment] 2017-08-16 11:25
I only tried the signed one and didn't saw that you needed to add a new value in the config.

It works with the added value, thanks! @jonathanKingston
