### ISSUE TITLE
Custom container disappeared after restart/update Nightly

### ISSUE THREAD

**Issue by youwenliang** [mozilla/testpilot-containers#403] opened 2017-03-24 03:54 UTC
I have a custom container with several work-related tabs, and after a few updates in Nightly, the custom container disappeared from the container list, but the tabs that were once inside the container remains, they just turned into normal tabs. Not sure how it happened.

**Comment by groovecoder** [comment] 2017-03-24 13:53
Possible dupe of https://github.com/mozilla/testpilot-containers/issues/374 ... do you remember if you were on a 1.x branch when Nightly updated?

**Comment by jonathanKingston** [comment] 2017-03-24 17:17
@youwenliang could you check about:support and see what version you are on of the experiment? If you are now on version 2.0 this bug should be now fixed for any further updates that we push of the experiment.

**Comment by youwenliang** [comment] 2017-03-27 02:33
@jasonthomas  Yes, I'm on version 2.0 now. I was probably on a 1.x branch before the update since I installed containers right when it started.

**Comment by groovecoder** [comment] 2017-03-27 16:00
Closing as dupe of bug #374. Sorry. 😢 Please re-open if this happens in some other upgrade.

**Closed** 2017-03-27 16:00 UTC
Labels: bug, duplicate
