### ISSUE TITLE
Context menu "Always Open in This Container" does not update until tab switch

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/testpilot-containers#539] opened 2017-05-26 07:35 UTC
Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0 ID:20170525100253 CSet: 0ed0fd886134b6698f593edbf0d362ac9e12fe07

After the update, which added the option to pin sites to containers, I gave it a try and noticed weird behavior, that the context menu does not update until I switch the tabs.

STR:
1. Open a new container tab (i.e. personal).
2. Go to first page (i.e. twitter.com) and mark it to always open in this container.
3. Go to a second page (i.e. tweetdeck.twitter.com).
4. Right-click to open the context menu and see, the always open in this container menu item is "checked", despite tweetdeck won't open in this container by default, only twitter.

**Comment by jonathanKingston** [comment] 2017-05-26 09:55
@MikkCZ hmm I can't replicate, I know we have some issues like this already.

- Is 3. in personal also?
- Is 1. and 2. in different windows

I think this is a dupe of #423 but I can only replicate across windows personally.

**Comment by MikkCZ** [comment] 2017-05-26 10:09
All step 2-4 are in the same tab you open in step 1. When I switch to another tab and back, the "check" disappears as expected.

I wonder if this cannot be in combination with Tab Center, which recently has some issues in Nightly. But I am not at my laptop at this moment to test.

**Comment by jonathanKingston** [comment] 2017-05-26 10:26
@MikkCZ ah, is 3 straight after clicking a link then?

I think that is similar to the window focus issue in that we don't have a hook to rewrite the text in the context menu. I can look into if there is a tab update hook to fix here.

**Comment by MikkCZ** [comment] 2017-05-26 10:44
Yes, it is.

**Closed** 2017-06-13 16:41 UTC
Labels: assignment, bug, context menu, has PR
