### ISSUE TITLE
Feature request: Create container from website, using its icon

### ISSUE THREAD

**Issue by martinruenz** [mozilla/testpilot-containers#841] opened 2017-09-20 13:36 UTC
Sometimes it is useful to have containers for individual webpages, but the current setup process for new containers doesn't really fit this use-case optimally.
I think the following approach would be nice:
* Having an open tab (potentially with login-data), you can right-click the tab and choose **move to new container**
* A new container is created, using the icon of the page (the color could also be picked automatically) and the tab is seamlessly converted, in order to belong to the new container
* Ideally, the new container would also keep login-information for the particular page. One would have to be careful, however, which cookies to copy -- otherwise, the isolation might get undermined.

**Comment by groovecoder** [comment] 2017-09-20 13:55
Duplicate of https://github.com/mozilla/testpilot-containers/issues/311. A consensus there is to use Context Plus for this purpose:

https://addons.mozilla.org/nn-no/firefox/addon/context-plus/

**Closed by groovecoder** 2017-09-20 13:55 UTC

**Comment by martinruenz** [comment] 2017-09-20 14:00
Oh, I didn't find this when searching the issues, thanks!
My proposal is slightly different though, I would like to see a feature to create a new container on the fly. Not to move a tab to an existing container.

**Comment by groovecoder** [comment] 2017-09-20 14:15
Another popular request. :) https://addons.mozilla.org/en-us/firefox/addon/containers-on-the-go/ tries to do this, though I don't think it preserves login information?

**Comment by martinruenz** [comment] 2017-09-20 14:17
Thanks!
