### ISSUE TITLE
View source not working

### ISSUE THREAD

**Issue by Alex-Dcat** [mozilla/testpilot-containers#594] opened 2017-06-15 14:17 UTC
Displays the source code for a window without a container.

**Comment by jonathanKingston** [comment] 2017-06-15 14:19
Duplicate of: #345 which is a duplicate of the platform bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1347604

**Closed by jonathanKingston** 2017-06-15 14:19 UTC
Labels: duplicate

**Comment by jonathanKingston** [comment] 2017-06-15 14:21
This looks like it is fixed in everything but stable also, so should work soon :). Thank you for the report though.

**Comment by Alex-Dcat** [comment] 2017-06-15 14:57
Not fixed in 53.0.3 and 54. Fixed in 55.0b1. But the tab view-source: does not contain the color line of the container.

**Comment by ftzdomino** [comment] 2018-04-05 22:05
I'm experiencing this in 59.0.2.  On any site in a container requiring authentication viewing the source appears to open in a different container and show me a login page.
