### ISSUE TITLE
Ability to move default container tab to a named container

### ISSUE THREAD

**Issue by thomasandersen** [mozilla/testpilot-containers#344] opened 2017-03-07 11:12 UTC
Using Developer Edition 53.0a2 (2017-03-05) (64-bit)

Would it be an idea to be able to move a new or existing tab from 'default' to a 'named' container? 

Example scenario:

1. Open a new regular tab. 
2. Right click on the tab or select File from menu
3. Select 'Move Tab to Container' > [containers menu]
4. Select 'Personal' container

Result: tab is moved to Personal container.

I guess this goes for moving to containers in general. 
Eg. move tab from 'Personal' to 'Finance'

The ambiguous way would be to drag'n drop tabs between containers from the container manager / menu.

**Comment by jonathanKingston** [comment] 2017-04-05 14:26
Thanks for the submission.
This is actually a duplicate of #311 sorry we missed this.

Please reopen if this is not the case.

**Closed by jonathanKingston** 2017-04-05 14:26 UTC
