### ISSUE TITLE
Activity Streams is not activated in containers

### ISSUE THREAD

**Issue by jgomo3** [mozilla/testpilot-containers#445] opened 2017-04-11 18:53 UTC
I enabled first containers then Activity Streams.

When oppening a tab in any of the containers (personal, work, etc.) The Activity Stream is not enabled. Only when opening a tab without a container (with simply Ctrl-C) I can see the Activity Stream.

Aside: Ctrl-Tab should open a tab in the current container.

**Comment by groovecoder** [comment] 2017-04-11 19:12
This seems like a duplicate of https://github.com/mozilla/testpilot-containers/issues/246. Please upvote there.

**Closed by groovecoder** 2017-04-11 19:12 UTC
