### ISSUE TITLE
Feature request: Move existing tab into container

### ISSUE THREAD

**Issue by aequis** [mozilla/testpilot-containers#694] opened 2017-07-27 09:49 UTC
I'm continuously running into the issue that I'll open a link to a certain site where I realize I want that site to be in one of my containers. But in order to do so, I have to open a new tab in the container I want, then copy and paste the address. Ideally, there'd be a right-click context menu option or an option in the addon tooltip that would let me move the tab into a container without extra steps.

**Comment by groovecoder** [comment] 2017-07-27 12:46
This is a common request, and sounds like a duplicate of https://github.com/mozilla/testpilot-containers/issues/311 and https://github.com/mozilla/testpilot-containers/issues/661. Please upvote those issues and see the comments there for some work-arounds.

**Closed by groovecoder** 2017-07-27 12:46 UTC

**Comment by jonathanKingston** [comment] 2017-08-02 14:22
See the following wiki page: https://github.com/mozilla/testpilot-containers/wiki/Moving-between-containers for more explanation.
