### ISSUE TITLE
Firefox Multi-Account Containers hiding incompatibility with Containers On The Go 1.11

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/testpilot-containers#816] opened 2017-09-14 06:34 UTC
A [Containers On The Go](https://addons.mozilla.org/en-us/firefox/addon/containers-on-the-go/) container is lost without warning when hidden by Firefox Multi-Account Containers.

**Comment by groovecoder** [comment] 2017-09-14 13:45
This is a symptom duplicate of https://github.com/mozilla/testpilot-containers/issues/802. Please upvote and comment there.

**Closed by groovecoder** 2017-09-14 13:45 UTC

**Comment by grahamperrin** [comment] 2017-09-14 15:19
Thanks, I missed that one. Apologies for the noise.
