### ISSUE TITLE
Make sure add-on can enable/disable contextualIdentity

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot-containers#651] opened 2017-06-30 17:02 UTC
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1354602

**Comment by businessBoris** [comment] 2017-07-03 09:44
[There are two possible addons that are causing problems, hopefully I have the correct one! 
The other one is "Context Plus". Apologies if not and please let me know. ]

I moved a tab to a context/container ("blah") and selected "always open in this container" for the page (on the right click). Whilst trying to find the cause of another problem, I disabled your addon forgetting that disabling it causes to forget any and all of the previous contained tabs, the names of the containers etc.

I now have a tab that won't let me move it to its "correct" container (having created a new list in the containers addon) and when I try to create the tab in a container tab asks me "Should we open this in your container?". It doesn't give me the option to say no and, without ticking the "Remember my decision for this site" checkbox, still moves the tab _out_ of the requested container to where it shouldn't be!

HELP please! Hopefully the context allocation(s) isn't binary format!

1/ Cannot cancel/view the context allocations. Perhaps a list in the icon menus?
2/ "Should we open this in your container?" page doesn't serve its purpose in multiple ways.

**Comment by businessBoris** [comment] 2017-07-03 15:39
For anyone else stuck in this little loop: quite an easy fix.
~/.mozilla/firefox/<profile directory>/browser-extension-data/@testpilot-containers/storage.js
should be moved to a different place/deleted.

**Comment by jonathanKingston** [comment] 2017-08-30 18:11
Fixed in central.

**Closed by jonathanKingston** 2017-08-30 18:11 UTC
