### ISSUE TITLE
Containers clipped in Options menu

### ISSUE THREAD

**Issue by aplatypus** [mozilla/testpilot-containers#316] opened 2017-03-02 22:39 UTC
Hello ...

I like to keep my browser simple.  So I put the Containers button into the Options (hamburger) menu.  When you click on the icon though it is Extremely clipped.  And virtually unusable.

**Comment by groovecoder** [comment] 2017-03-02 22:56
Duplicate of https://github.com/mozilla/testpilot-containers/issues/259 - can you 👍 that issue?

**Closed by groovecoder** 2017-03-02 22:56 UTC
