### ISSUE TITLE
Manage all assigned links

### ISSUE THREAD

**Issue by imyxh** [mozilla/testpilot-containers#455] opened 2017-04-18 02:41 UTC
Just a suggestion.
Maybe there should be a place, either in the containers addon preferences or in the main preferences, where you can manage all of your assigned tabs and their containers.
Sort of like the "Saved Logins" button on the "Security" section of the preferences, except with more freedom to edit the assigned containers.

![image](https://cloud.githubusercontent.com/assets/12703838/25112413/cbb236f8-23a5-11e7-8a12-881d6bd191dc.png)

**Comment by jonathanKingston** [comment] 2017-04-19 16:41
Duplicate of #425 please add further comments there 👍

**Closed by jonathanKingston** 2017-04-19 16:41 UTC
