### ISSUE TITLE
"Open in Current Container" option is not working in new windows

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot-containers#610] opened 2017-06-21 13:23 UTC
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]
- Have the latest Containers version installed on a new Firefox profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and visit any website in a new container.
2. Right click on the page and choose the "Always Open in This Container" option.
3. Open a new window (Ctrl+N) and navigate to the same website from step 1.
5. Click the "Open in Current Container" button.
6. Observe the browser behavior.

[Expected result]:
- The website is opened in the current container tab.

[Actual results]:
- The "Containers confirm navigation" page is opened in a new tab, but the website is not loaded in any containers.

[Notes]:
- Here is a screen recording with the issue:
![open in current container](https://user-images.githubusercontent.com/19226534/27386218-c8bffba8-569d-11e7-8c75-43b0a1802393.gif)

**Comment by kjozwiak** [comment] 2017-06-21 15:43
Duplicate of #606.

**Closed by kjozwiak** 2017-06-21 15:43 UTC
Labels: bug, shield
