### ISSUE TITLE
After hiding and showing Container it opens duplicates

### ISSUE THREAD

**Issue by Daresch** [mozilla/testpilot-containers#825] opened 2017-09-17 07:56 UTC
If there is more than one tab open in a container, the addon does the following:
* click on "Hide this container": All tabs of the container are closed
* click on "Show this container": All tabs of the container are opened in this container, but additionally it opens duplicates of tabs in this container. So every URL is opened twice in the same container.

Tested with
* Firefox 55.0.2 (64bit) on Ubuntu 16.04
* Multi-Account Containers 4.0.2

**Comment by groovecoder** [comment] 2017-09-17 12:31
Dupe of https://github.com/mozilla/testpilot-containers/issues/791. Should be fixed in 4.0.2 when it's reviewed an approved by AMO team.

**Closed by groovecoder** 2017-09-17 12:31 UTC
