### ISSUE TITLE
Container tabs interfere with cookies in non-container tabs for same site and vice-versa

### ISSUE THREAD

**Issue by vcchappell** [mozilla/testpilot-containers#482] opened 2017-05-06 01:08 UTC
I log into eBay account #1 in a tab with no container.
All day long I can exit and restart Firefox, I am still logged in.

I log into eBay account #2 in a tab in Container 1.
Next time I restart Firefox, I am still logged in to eBay account #2 in Container 1, but now logged out of eBay account #1 in the tab with no container.  The session cookie for the containerless tab got lost.

So if I then log into eBay account #1 again, next time I restart, I am logged out of eBay account #2.

So it seems that the session cookie for a given is preserved only for the latest login.  I thought the cookies were stored independently for sites in Containers?

The Container should not interfere with the cookies of non-container sites, and vice-versa.

**Comment by jonathanKingston** [comment] 2017-05-06 06:57
This looks like a duplicate of #397. Thanks

**Closed by jonathanKingston** 2017-05-06 06:57 UTC
