### ISSUE TITLE
Opening a link in a new tab focuses it when it switches container

### ISSUE THREAD

**Issue by gibfahn** [mozilla/testpilot-containers#798] opened 2017-09-07 17:33 UTC
If I middle click on a URL that defaults to a different container, when the newly opened (background) tab automatically switches to its default container, it gets focused.

This is a bit of a pain for me, as I use [Snap Links](https://github.com/cpriest/SnapLinksPlus) to bulk open my [Github notifications](https://github.com/notifications) in new tabs, which then means the focused tab jumps between every tab opened (instead of quietly opening in the background).

### Current behaviour:

![contfocus1](https://user-images.githubusercontent.com/15943089/30176441-58ab6c36-93fa-11e7-9592-9c4f4aa5cceb.gif)

### Ideal behaviour:

This currently works when the old and new tab default to the same container.

![contfocus2](https://user-images.githubusercontent.com/15943089/30176445-5cb2ae20-93fa-11e7-9dc6-8622ddb68b54.gif)

**Comment by jonathanKingston** [comment] 2017-09-07 17:59
This is a duplicate of #442 thanks for raising with the images. Feel free to add those there and subscribe to that. Thanks

**Closed by jonathanKingston** 2017-09-07 17:59 UTC
