### ISSUE TITLE
"When Nightly starts: Show your home page" doesn't use "Always Open in This Container"

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#533] opened 2017-05-24 20:16 UTC
When setting a homepage that belongs to a specific container via about:preferences, the website won't open in the specified container when FX is launched.

STR:

* install fx and the [containers experiment](https://testpilot.firefox.com/experiments/containers) via [test pilot](https://testpilot.firefox.com/) (either 2.2.0 or 2.3.0)
* open a personal container and visit facebook.com
* right click on facebook.com and select `Always Open in This Container`
* close the personal tab and visit `about:preferences`
* select `When Nightly starts: Show your homepage` and under `Home Page:` use facebook.com
* restart fx

You'll notice that the facebook.com page is being loaded in the default contianer.

**Comment by jonathanKingston** [comment] 2017-05-24 20:20
Looks like a dupe of: #474 where the home page doesn't go through the web extensions detection first.

**Closed** 2017-05-24 20:21 UTC
Labels: bug
