### ISSUE TITLE
Cookies in containers are not isolated

### ISSUE THREAD

**Issue by SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU** [mozilla/testpilot-containers#404] opened 2017-03-26 01:09 UTC
On the site vk.com, cookies are copied outside the container.
To reproduce:
1. Open page https://vk.com/ in container.
2. Look where all the cookies hit.

**Comment by jonathanKingston** [comment] 2017-03-27 14:20
I can't replicate this at all, I have tried many different ways. Can you paste about:support output.

@kjozwiak have you seen this?

**Comment by kjozwiak** [comment] 2017-03-28 18:32
I couldn't reproduce this on any of the channels. I created an account under vk.com, logged in and made sure that the cookies were being assigned the correct userContextId... Checked using:

* about:preferences#privacy -> remove individual cookies
* cookies.sqlite database and ensured cookies are using the correct ^userContextId=

<img width="490" alt="screen shot 2017-03-28 at 1 33 23 pm" src="https://cloud.githubusercontent.com/assets/2602313/24419937/000a6a84-13bf-11e7-8c2e-5d535d40f1bf.png">

Used the following builds:

* fx52.0.2, buildid: 20170323105023, changeset: e81854d6ce91 - couldn't reproduce
* fx53.0b7, buildid: 20170327081421, changeset: 46d5fe92c82d - couldn't reproduce
* fx54.0a2, buildid: 20170328004003, changeset: db2babffcafb - couldn't reproduce
* fx55.0a1, buildid: 20170328030207, changeset: 5182b2c4b963 - couldn't reproduce

@SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU, would you be able to provide us with a some more information? Which version of firefox are you using? Which version of the test pilot are you using? As @jonathanKingston mentioned above, you can find all this information under about:support.

When you're logging into vk.com, could you check your cookies under about:preferences#privacy and click on "remove individual cookies". You should see all the cookies that are from vk.com being associated with the container that's currently being used, example:

<img width="572" alt="screen shot 2017-03-28 at 1 52 21 pm" src="https://cloud.githubusercontent.com/assets/2602313/24419694/ffed5ef4-13bd-11e7-8c2b-f289c3f1b3a9.png">

Are you seeing something different? Are you using other add-ons/extensions by any chance? Could it be possible that you've accidently opened vk.com in the default container?

**Comment by jonathanKingston** [comment] 2017-04-05 11:01
Closing this as we can't replicate. Feel free to reopen if this is not the case as we certainly would want to catch these issues with the highest priority.

**Closed by jonathanKingston** 2017-04-05 11:01 UTC
Labels: bug, question

**Comment by zesty** [comment] 2024-10-29 18:20
What am I missing? I can trivially reproduce cross-container and outside container sharing of cookies for a single site:

3 tabs:
1 - container 1
2 - container 2
3 - no container

Load cnn.com in all 3 and open dev tools. Open storage -> cookies -> cnn.com
Update the value of the wbdFch cookie (pick any one, but some of them are updated dynamically and often).
See the value change in the other two tabs.

Am I not understanding how this is supposed to work? Is developer tools unaware of containers when writing data?
