### ISSUE TITLE
Hovering over New Tab container categories collapses Tab Center

### ISSUE THREAD

**Issue by Omniscimus** [mozilla/testpilot-containers#384] opened 2017-03-15 18:59 UTC
This bug occurs when using both Containers and Tab Center.

OS: macOS 10.12.3
Firefox version: 54.0a2 (2017-03-15) (64-bit)

Steps to reproduce:
- Install Test Pilot
- Install Tab Center via Test Pilot
- Install Containers via Test Pilot and create some container categories
- Make sure that the Tab Center auto-collapses: in Tab Center, click the "Shrink sidebar when not in use" button
- In Tab Center, hover your mouse over "+ New Tab". The menu of containers will appear. Hover your mouse over one of the container categories. The Tab Center will now collapse, and the containers menu will move to the left.

I'd expect the Tab Center sidebar to just stay open while I'm selecting the container for my new tab. Because the containers menu also moves to the left, this causes it to move off-screen if the browser is not in full-screen mode.

**Comment by bunnybooboo** [comment] 2017-03-24 11:25
#335

**Comment by bunnybooboo** [comment] 2017-03-24 11:25
Related to #335 ?

**Comment by kjozwiak** [comment] 2017-04-26 22:49
@Omniscimus, are you referring to the Tab Center being hidden/dismissed when hovering over the containers. Something similar to [this](https://github.com/bwinton/TabCenter/issues/1066)? I'm not sure if there's anything we can do about that as it's most likely an issue with the Tab Center. It appears like there's already a bug created for this exact issue under [here](https://github.com/bwinton/TabCenter/issues/1066).

In regards to the menu being shifted to the left, this is intended behaviour so that the un-rounded hit-target stays directly under the mouse position which was mentioned by @groovecoder in the following [bug](https://github.com/mozilla/testpilot-containers/issues/335#issuecomment-285753150).

Closing this issue. @groovecoder, please re-open if you disagree with the above.

**Closed by kjozwiak** 2017-04-26 22:49 UTC
Labels: addon incompatibility, bug
