### ISSUE TITLE
Make new tab menu items less rounded

### ISSUE THREAD

**Issue by Keith94** [mozilla/testpilot-containers#619] opened 2017-06-22 04:44 UTC
`border-radius: 20px` seems way too rounded and doesn't fit the rest of the UI; can you consider reducing it, maybe something like 4px or 6px?

**Comment by jonathanKingston** [comment] 2017-06-22 10:51
Thank you for the suggestion this is however a duplicate of: #433 which is a much neater UX that we will be working on soon.

**Closed by jonathanKingston** 2017-06-22 10:51 UTC
Labels: duplicate, enhancement
