### ISSUE TITLE
Please consider creating a "default" profile.

### ISSUE THREAD

**Issue by albertoefg** [mozilla/testpilot-containers#465] opened 2017-04-26 04:00 UTC
This might seem silly, as the "no profile" might be its own container. But I am asking for this because I usually don't remember about containers when I open Firefox. 

I think that by having a default container, and seeing the tabs with a different color, as soon as I open Firefox, could remind me that I have containers and I can use them! 

You might say that the icon could remind me, but I am using Nightly which already has this option by default and no icon is showing on the bar.

**Comment by anewuser** [comment] 2017-04-26 04:56
Duplicate of https://github.com/mozilla/testpilot-containers/issues/356

**Comment by groovecoder** [comment] 2017-04-26 15:22
Closing as dupe of #356. @albertoefg - can you upvote there and add comments?

**Closed by groovecoder** 2017-04-26 15:22 UTC
