### ISSUE TITLE
Menu doesn't like black theme (GTK themes, Linux)

### ISSUE THREAD

**Issue by D219** [mozilla/testpilot-containers#695] opened 2017-07-27 11:11 UTC
Using a black theme (Bunsen-Blackish) in BunsenLabs (Debian Jessie  Openbox) result in:

![screenshot - 270717 - 12 29 21](https://user-images.githubusercontent.com/5468479/28667646-b6cd4bc6-72cc-11e7-9494-4092437982a7.png)

(Don't mind the Iceweasel branding, it is a add on)

{
  "application": {
    "name": "Firefox",
    "osVersion": "Linux 4.9.0-0.bpo.3-amd64",
    "version": "54.0.1",
    "buildID": "20170628145605",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0",
    "safeMode": false,
    "updateChannel": "release",
    "supportURL": "https://support.mozilla.org/1/firefox/54.0.1/Linux/en-US/",
    "numTotalWindows": 1,
    "numRemoteWindows": 0,
    "remoteAutoStart": false,
    "autoStartStatus": 7,
    "keyGoogleFound": true,
    "keyMozillaFound": true
  },
  "modifiedPreferences": {
    "accessibility.typeaheadfind.flashBar": 0,
    "browser.cache.disk.smart_size.first_run": false,
    "browser.cache.disk.smart_size.use_old_max": false,
    "browser.cache.disk.filesystem_reported": 1,
    "browser.cache.disk.capacity": 358400,
    "browser.cache.frecency_experiment": 1,
    "browser.download.importedFromSqlite": true,
    "browser.places.smartBookmarksVersion": 8,
    "browser.search.useDBForOrder": true,
    "browser.sessionstore.upgradeBackup.latestBuildID": "20170628145605",
    "browser.startup.homepage_override.buildID": "20170628145605",
    "browser.startup.homepage_override.mstone": "54.0.1",
    "browser.tabs.remote.autostart.2": true,
    "browser.tabs.animate": false,
    "browser.urlbar.lastSuggestionsPromptDate": 20170327,
    "browser.urlbar.suggest.searches": true,
    "browser.urlbar.daysBeforeHidingSuggestionsPrompt": 3,
    "dom.apps.reset-permissions": true,
    "dom.mozApps.used": true,
    "extensions.lastAppVersion": "54.0.1",
    "font.internaluseonly.changed": false,
    "gfx.crash-guard.glcontext.driverVersion": "3.0 Mesa 10.3.2",
    "gfx.crash-guard.glcontext.deviceID": "Gallium 0.4 on llvmpipe (LLVM 3.5, 128 bits)",
    "gfx.crash-guard.glcontext.appVersion": "45.8.0",
    "gfx.crash-guard.status.glcontext": 2,
    "media.eme.enabled": true,
    "media.gmp-widevinecdm.lastUpdate": 1495842773,
    "media.gmp-gmpopenh264.lastUpdate": 1491376041,
    "media.gmp-gmpopenh264.version": "1.6",
    "media.gmp-widevinecdm.abi": "x86_64-gcc3",
    "media.gmp-manager.lastCheck": 1501150504,
    "media.gmp-widevinecdm.version": "1.4.8.903",
    "media.gmp.storage.version.observed": 1,
    "media.gmp-gmpopenh264.abi": "x86_64-gcc3",
    "media.gmp-manager.buildID": "20170628145605",
    "network.prefetch-next": false,
    "network.dns.disablePrefetch": true,
    "network.http.speculative-parallel-limit": 0,
    "network.predictor.cleaned-up": true,
    "network.cookie.prefsMigrated": true,
    "places.database.lastMaintenance": 1500541859,
    "places.history.expiration.transient_current_max_pages": 91636,
    "plugin.disable_full_page_plugin_for_types": "application/pdf",
    "privacy.usercontext.about_newtab_segregation.enabled": true,
    "privacy.userContext.enabled": true,
    "privacy.userContext.longPressBehavior": 2,
    "privacy.sanitize.migrateFx3Prefs": true,
    "services.sync.declinedEngines": "",
    "storage.vacuum.last.places.sqlite": 1499075961,
    "storage.vacuum.last.index": 1
  },
  "lockedPreferences": {},
  "javaScript": {
    "incrementalGCEnabled": true
  },
  "accessibility": {
    "isActive": false,
    "forceDisabled": 0
  },
  "libraryVersions": {
    "NSPR": {
      "minVersion": "4.14",
      "version": "4.14"
    },
    "NSS": {
      "minVersion": "3.30.2",
      "version": "3.30.2"
    },
    "NSSUTIL": {
      "minVersion": "3.30.2",
      "version": "3.30.2"
    },
    "NSSSSL": {
      "minVersion": "3.30.2",
      "version": "3.30.2"
    },
    "NSSSMIME": {
      "minVersion": "3.30.2",
      "version": "3.30.2"
    }
  },
  "userJS": {
    "exists": false
  },
  "crashes": {
    "submitted": [],
    "pending": 0
  },
  "sandbox": {
    "hasSeccompBPF": true,
    "hasSeccompTSync": true,
    "hasPrivilegedUserNamespaces": true,
    "hasUserNamespaces": false,
    "canSandboxContent": true,
    "canSandboxMedia": true,
    "syscallLog": [],
    "contentSandboxLevel": 2
  },
  "experiments": [],
  "extensions": [
    {
      "name": "Application Update Service Helper",
      "version": "2.0",
      "isActive": true,
      "id": "aushelper@mozilla.org"
    },
    {
      "name": "Containers Experiment",
      "version": "2.4.0",
      "isActive": true,
      "id": "@testpilot-containers"
    },
    {
      "name": "Enhancer for YouTube™",
      "version": "2.0.17",
      "isActive": true,
      "id": "enhancerforyoutube@maximerf.addons.mozilla.org"
    },
    {
      "name": "Firefox Screenshots",
      "version": "6.6.0",
      "isActive": true,
      "id": "screenshots@mozilla.org"
    },
    {
      "name": "FlashGot",
      "version": "1.5.6.14",
      "isActive": true,
      "id": "{19503e42-ca3c-4c27-b1e2-9cdb2170ee34}"
    },
    {
      "name": "Iceweasel Branding",
      "version": "0.3.3",
      "isActive": true,
      "id": "iceweasel-branding@mozilla.debian.net"
    },
    {
      "name": "JSON Lite",
      "version": "0.20",
      "isActive": true,
      "id": "{16a49f65-1369-4839-a5ef-db2581e08b16}"
    },
    {
      "name": "KeeFox",
      "version": "1.6.4",
      "isActive": true,
      "id": "keefox@chris.tomlinson"
    },
    {
      "name": "Min Vid",
      "version": "0.3.8",
      "isActive": true,
      "id": "@min-vid"
    },
    {
      "name": "Multi-process staged rollout",
      "version": "1.50",
      "isActive": true,
      "id": "e10srollout@mozilla.org"
    },
    {
      "name": "NoScript",
      "version": "5.0.7.1",
      "isActive": true,
      "id": "{73a6fe31-595d-460b-a920-fcc0f8843232}"
    },
    {
      "name": "Pocket",
      "version": "1.0.5",
      "isActive": true,
      "id": "firefox@getpocket.com"
    },
    {
      "name": "Tab Center",
      "version": "1.36.0",
      "isActive": true,
      "id": "tabcentertest1@mozilla.com"
    },
    {
      "name": "Test Pilot",
      "version": "1.1.4-dev-ead6dcd",
      "isActive": true,
      "id": "@testpilot-addon"
    },
    {
      "name": "uBlock Origin",
      "version": "1.13.8",
      "isActive": true,
      "id": "uBlock0@raymondhill.net"
    },
    {
      "name": "Wayback Machine",
      "version": "1.8.1",
      "isActive": true,
      "id": "wayback_machine@mozilla.org"
    },
    {
      "name": "Web Compat",
      "version": "1.1",
      "isActive": true,
      "id": "webcompat@mozilla.org"
    },
    {
      "name": "Open With",
      "version": "6.8.1",
      "isActive": false,
      "id": "openwith@darktrojan.net"
    }
  ],
  "graphics": {
    "numTotalWindows": 1,
    "numAcceleratedWindows": 0,
    "windowLayerManagerType": "Basic",
    "windowLayerManagerRemote": true,
    "currentAudioBackend": "pulse",
    "numAcceleratedWindowsMessage": [
      "blockedGfxCard"
    ],
    "adapterDescription": "VMware, Inc. -- Gallium 0.4 on llvmpipe (LLVM 3.5, 128 bits)",
    "adapterVendorID": "VMware, Inc.",
    "adapterDeviceID": "Gallium 0.4 on llvmpipe (LLVM 3.5, 128 bits)",
    "adapterRAM": "",
    "adapterDrivers": "",
    "driverVersion": "3.0 Mesa 10.3.2",
    "driverDate": "",
    "webgl1Renderer": "VMware, Inc. -- Gallium 0.4 on llvmpipe (LLVM 3.5, 128 bits)",
    "webgl1Version": "3.0 Mesa 10.3.2",
    "webgl1DriverExtensions": "GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_polygon_offset GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_NV_fog_distance GL_APPLE_packed_pixels GL_APPLE_vertex_array_object GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_MESA_ycbcr_texture GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_ATI_texture_compression_3dc GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_ATI_texture_mirror_once GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_texture_array GL_EXT_texture_compression_latc GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_texture_lod GL_ARB_texture_multisample GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_shader_trinary_minmax GL_ARB_ES3_compatibility GL_ARB_clear_buffer_object GL_ARB_explicit_uniform_location GL_ARB_invalidate_subdata GL_ARB_stencil_texturing GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_vertex_attrib_binding GL_KHR_debug GL_ARB_multi_bind GL_ARB_seamless_cubemap_per_texture GL_ARB_texture_mirror_clamp_to_edge GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_integer_mix GL_ARB_conditional_render_inverted ",
    "webgl1Extensions": "ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_frag_depth EXT_sRGB EXT_shader_texture_lod EXT_disjoint_timer_query MOZ_debug_get OES_element_index_uint OES_standard_derivatives OES_texture_float OES_texture_float_linear OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_etc WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_draw_buffers WEBGL_lose_context MOZ_WEBGL_lose_context MOZ_WEBGL_depth_texture",
    "webgl1WSIInfo": "GLX 1.4\nGLX_VENDOR(client): Mesa Project and SGI\nGLX_VENDOR(server): SGI\nExtensions: GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_import_context GLX_EXT_visual_info GLX_EXT_visual_rating GLX_MESA_copy_sub_buffer GLX_MESA_multithread_makecurrent GLX_MESA_query_renderer GLX_OML_swap_method GLX_SGI_make_current_read GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_EXT_texture_from_pixmap ",
    "webgl2Renderer": "WebGL creation failed: \n* Error during native OpenGL init.\n* WebGL 2 requires support for the following features: \n  get_integer64_indexed\n* Exhausted GL driver options.",
    "webgl2Version": "-",
    "webgl2DriverExtensions": "-",
    "webgl2Extensions": "-",
    "webgl2WSIInfo": "-",
    "info": {
      "AzureCanvasBackend": "skia",
      "AzureFallbackCanvasBackend": "none",
      "AzureContentBackend": "skia",
      "AzureCanvasAccelerated": 0,
      "CairoUseXRender": 0
    },
    "featureLog": {
      "features": [
        {
          "name": "HW_COMPOSITING",
          "description": "Compositing",
          "status": "blocked",
          "log": [
            {
              "type": "default",
              "status": "blocked",
              "message": "Acceleration blocked by platform"
            }
          ]
        },
        {
          "name": "OPENGL_COMPOSITING",
          "description": "OpenGL Compositing",
          "status": "unavailable",
          "log": [
            {
              "type": "default",
              "status": "unavailable",
              "message": "Hardware compositing is disabled"
            }
          ]
        },
        {
          "name": "WEBRENDER",
          "description": "WebRender",
          "status": "unavailable",
          "log": [
            {
              "type": "default",
              "status": "available"
            },
            {
              "type": "runtime",
              "status": "unavailable",
              "message": "Build doesn't include WebRender"
            }
          ]
        }
      ],
      "fallbacks": []
    },
    "crashGuards": []
  }
}

**Comment by groovecoder** [comment] 2017-07-27 12:49
Dupe of https://github.com/mozilla/testpilot-containers/issues/677. The fix (https://github.com/mozilla/testpilot-containers/pull/681) is merged. It should be released Soon™.

**Closed by groovecoder** 2017-07-27 12:49 UTC
