### ISSUE TITLE
New Container Tab fails to open at all (new as of several days)

### ISSUE THREAD

**Issue by yareckon** [mozilla/testpilot-containers#548] opened 2017-05-28 20:01 UTC
Since several days in firefox developer edition new container tabs fail to open at all.  Starting firefox developer edition from the commandline doesn't result in any errors to standard out when the container tab fails to open. 
I have disabled and reinstalled the containers feature (losing my named containers in the process), but the problem persists.  When picking the container name, the container drawer closes, but no new tab is opened.

**Comment by yareckon** [comment] 2017-05-28 20:07
Oh noes, just saw https://github.com/mozilla/testpilot-containers/issues/469 and that Permanent Private mode is not supported!  It has worked until the last few days though.  It broke around the time the tabs icon inside the containers flyout was added.

**Comment by yareckon** [comment] 2017-05-28 20:48
The reason that permanent private browsing mode is indispensable over and above the settings to not remember history and to toss out cookies is that tracking protection is only turned on in private mode by default in firefox.  Please don't make us choose between tracking protection and containers -- they should by rights be complementary.  

Of course private browsing mode always folks should also understand that they can't use every feature of containers that are incompatible with the concept of private browsing mode, i.e. they can't set a domain to always open in a certain container, because the idea of private browsing mode is not to save any data about where you've been on your computer.  That means there is no "there" there to save that setting to.

**Comment by jonathanKingston** [comment] 2017-05-29 10:37
@yareckon please could you upvote and comment on #469 as this seems like a duplicate of that.

We prioritise work based on it's upvotes mostly, whilst I fully agree with you that containers should be in permanent private mode it's not where the majority of users are asking for this experiment (that is all this is, an experiment to see how successful things are and how we can expand adoption, what users like etc).

> It broke around the time the tabs icon inside the containers flyout was added.

I'm not sure which icon you mean?

**Closed by jonathanKingston** 2017-05-29 10:37 UTC
