### ISSUE TITLE
Bug in hover menu display (via 'Tab Center' test pilot?)

### ISSUE THREAD

**Issue by bunnybooboo** [mozilla/testpilot-containers#335] opened 2017-03-04 10:48 UTC
Mentioned this in test pilot feedback but adding here for consistency.

Even after re-enabling the containers test pilot due to [another bug](https://github.com/mozilla/testpilot-containers/issues/334) experienced I've managed to reproduce this:

Inconsistent behaviour on this bug however. When I hover to select a new container it usually works as expected. Every so often I select a new container, switch to a non-containerised tab, attempt the hover menu, and the menu is shunted over to the left - up to half way into the icons. (EDIT 3: Easily reproduced going to tabs [with tab center also enabled] to expand them with a hover, mouse to `+new tab`, hover)
![screenshot from 2017-03-04 10-33-30](https://cloud.githubusercontent.com/assets/5793295/23578112/4554ce1e-00c7-11e7-8b98-cecc0a3818ce.png)

(and actually on closer inspection it seems more complex and overall degradation)

Observed soon after this bug shows is the active tab blue highlight is now missing. In this example I have the 3rd tab down active.
![screenshot from 2017-03-04 10-46-12](https://cloud.githubusercontent.com/assets/5793295/23578139/0a4386c0-00c8-11e7-88b0-48d9f82c460a.png)

EDIT 1: Just done a full system restart and able to reproduce this bug within minutes. Though the blue active tab highlight is working this time, even with the hover menu shunting over. 
EDIT 2: After another system restart and now the 'Tab Center' test pilot is not reflecting the dark theme I have selected (the theme correctly shows in the address bar). Containers bug reproducible again. Wondering if this error comes via 'Tab Center' instead. On testing further, I disabled 'Tab Center' and experience no observed issues in horizontally aligned tabs. Even the dark theme switched back. Re-enabling 'Tab Center', hiccups for several seconds before finally showing the dark theme. I can quickly reproduce the shunted hover menu.

**Comment by jonathanKingston** [comment] 2017-03-05 17:29
I thinks this is related to Tab Centre Issues: https://github.com/mozilla/testpilot-containers/issues/229

**Comment by groovecoder** [comment] 2017-03-06 15:59
@bunnybooboo - can you confirm this is caused by tab centre issue? If so, I'd like to close this and #334 in favor of that issue, so we're not all working off different issues.

**Comment by groovecoder** [comment] 2017-03-07 13:27
@jonathanKingston - you added this to Sprint 1 milestone; does that mean you're working on it now? I.e., can it be assigned to you?

**Comment by groovecoder** [comment] 2017-03-10 18:52
WONTFIX ... we shift the menu over on purpose so that the un-rounded hit-target stays directly under the mouse position.

**Closed by groovecoder** 2017-03-10 18:52 UTC
Labels: addon incompatibility, bug
