### ISSUE TITLE
"Reload tab in container" context menu option

### ISSUE THREAD

**Issue by jeremiahlee** [mozilla/testpilot-containers#494] opened 2017-05-10 18:03 UTC
I occasionally open a URL in a generic tab or the unintended container. Please add a "reload tab in container > [available containers]" option in the right-click context menu.

**Comment by groovecoder** [comment] 2017-05-10 18:07
Duplicate of https://github.com/mozilla/testpilot-containers/issues/311

**Closed by groovecoder** 2017-05-10 18:07 UTC
