### ISSUE TITLE
Set default container for new page or tab

### ISSUE THREAD

**Issue by ibahnasy** [mozilla/testpilot-containers#526] opened 2017-05-23 05:07 UTC
There should be an option for a default container when Firefox starts, a program that opens a new page or tab.

**Comment by jonathanKingston** [comment] 2017-05-23 09:25
I think this is a duplicate of #356, feel free to reopen if you think it isn't.
Thank you for your interest in the project!

**Closed by jonathanKingston** 2017-05-23 09:25 UTC
