### ISSUE TITLE
"Always open in Default" is grayed out and unusable

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/testpilot-containers#612] opened 2017-06-21 14:22 UTC
[Affected versions]:
- Firefox 54.0.1 and up
- Containers 2.3.0 

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Containers add-on was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a website in a normal tab. (eg. www.reddit.com)
2. Click the Containers button from the browser toolbar.
3. Observe the "Always open in Default" option. 

[Expected result]:
- Option is clickable.

[Actual result]:
- Option is grayed out and unusable.

[Notes]:
- This option works in all other containers except the default one.
- Attached a screen recording of the issue:
![always open in default option unusable](https://user-images.githubusercontent.com/18304511/27388961-b706a1de-56a5-11e7-9cc1-811358cc1140.gif)

**Comment by kjozwiak** [comment] 2017-06-22 00:48
@jonathanKingston, I believe this is the intended behaviour as we don't allow users to assign particular websites to the default context. We've had similar requests as per #503.

If the above is true, we can close this off.

**Comment by jonathanKingston** [comment] 2017-06-22 02:00
As @kjozwiak mentioned this was intended, there was open questions about how we would let the user manage default assignments as there isn't a menu item for that so I didn't enable it by default.

We could possibly make a warning here but I personally think that it is greyed out will be clear enough to users for now.

**Closed by jonathanKingston** 2017-06-22 02:00 UTC
Labels: assignment, enhancement, Low, shield

**Comment by SoftVision-CiprianMuresan** [comment] 2017-06-22 09:12
In #503 the user story is about a context menu option for non-container tabs. This is about the doorhanger option to "Always open in Default" which looks like it's implemented, but it does not work.

I did some digging around because of #503. It looks like in the reported version (2.2.0) you were able to assign websites to a specific container (with the context menu option), but there is no mention of the assignment in the doorhanger. In the build we received (2.3.0), websites appear as assigned in the Containers doorhanger. 

@jonathanKingston, if the user cannot set a website to open in the default context I don't think that option should be displayed at all. Why show an option if you can't do anything with it?

**Comment by jonathanKingston** [comment] 2017-06-22 12:26
So #503 is about the restrictions on not being able to assign to default.
We could equally remove the interface as you mention but then it's less consistent across tabs in height.

>  but there is no mention of the assignment in the doorhanger

Yeah this is new as part of this release so wouldn't have existed then.

@johngruen @kjozwiak @groovecoder should we consider this post release. I don't think anything is broken here. We can start looking about solving the display issue mentioned in #503 which is a blocker to assigning default tabs.

**Comment by groovecoder** [comment] 2017-06-22 12:57
Agree it could and should be a post-release issue.

**Comment by binaryanomaly** [comment] 2017-08-08 17:43
I find the "as is" state confusing as well. It implies you could assign a "no container" default. Would appreciate that feature though. If the feature is not there rather nothing should be displayed, imho...

**Comment by evbarnett** [comment] 2018-07-20 01:23
I know this is an old thread- but I would like this feature.

**Comment by binaryanomaly** [comment] 2018-07-20 06:29
I would also still like it.
I think it could improve usability of containers as you would not have to care too much which tab/container you're in and could rely on that the website would always be opened in the defined, intended container which is not the case today if not another container is assigned explicitely.
If this is not going to be implemented at least don't display this option as it has no use and is meaningless in its current state of implementation.
