### ISSUE TITLE
Hiding container and then closing browser loses all tabs in that container

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/testpilot-containers#165] opened 2017-02-09 22:41 UTC
Can we make the local storage persistent?  So we don't lose the tabs.

**Comment by jonathanKingston** [comment] 2017-02-10 15:04
Looking into this 👍

**Comment by bakulf** [comment] 2017-02-10 15:04
Is this a duplicate of #156 ? See my last comment.
Reopen this issue if I'm wrong.

**Closed by bakulf** 2017-02-10 15:04 UTC
