### ISSUE TITLE
I would like to change the sequence of the containers if possible

### ISSUE THREAD

**Issue by niyali** [mozilla/testpilot-containers#405] opened 2017-03-29 06:30 UTC
It won't allow me to change the sequence of the containers unless I remove all and add them back in the sequence I prefer. 
Any chance you could make it easier to change the order?

Thank you very much.

**Comment by kjozwiak** [comment] 2017-03-29 17:35
@niyali, thanks for the feedback, definitely appreciated :) However, this is a duplicate of #330

**Closed** 2017-03-29 17:39 UTC
Labels: duplicate, enhancement
