### ISSUE TITLE
Feature : Move existing tab to a container

### ISSUE THREAD

**Issue by alain-andre** [mozilla/testpilot-containers#704] opened 2017-08-02 10:30 UTC
In order to organize my URLs<br>
I want to be able to affect a Container to an existing tab.

---
When I start using Container, I use to click on my bookmarks and the page open in a tab witch **is not** in any Container.

In order to make this URL open every times in a specific container, I **actually need** to 
- open bookmark in a tab (**Tab A**)
- copy the URL of the **Tab A**
- open a new tab with a specific (Personnal) container (**Tab B**)
- set the URL of the **Tab B**
- close the **Tab A**
- go to the Container manager
- Check the "always open in Personnal" for the **Tab B** 

**I would like to**
 - open bookmark in a tab (**Tab A**)
 - go to the Container manager
 - Move the tab to a specific Container
 - Check the "always open in " for the **Tab A** 

# Mock-up
![mockup](https://user-images.githubusercontent.com/3098101/28869831-507e5430-777e-11e7-8047-bd51e52a6890.png)

**Comment by jonathanKingston** [comment] 2017-08-02 13:45
I'm interested in what OS /FF version you have as the font looks wrong on the "move to" text.

However this is a duplicate of one of our most requested features:
https://github.com/mozilla/testpilot-containers/issues/311#issuecomment-306491003

I'm going to make a wiki page now as we get this requested so many times. Please see the comment above, I'm sorry it's not possible.

You can install the extension mentioned there however it's worth noting it will impact security/privacy.

Thanks

**Closed by jonathanKingston** 2017-08-02 13:45 UTC

**Comment by jonathanKingston** [comment] 2017-08-02 14:05
I created the [wiki page](https://github.com/mozilla/testpilot-containers/wiki/Moving-between-containers) which is perhaps clearer. Happy to answer questions to make it clearer though.

**Comment by alain-andre** [comment] 2017-08-02 15:02
Ho, ok. I looked for an issue talking about this feature but found nothing :( sorry for the duplicate issue.

The font of the text "Move to" is just a standard HTML page I did to insert it with gimp in my screenshot. It has nothing to do with the component font.

**Comment by jonathanKingston** [comment] 2017-08-02 15:19
Ah I see sorry I misunderstood the screenshot. Yeah that's the same issue
as the wiki page. No worries about the duplicate at all :)
