### ISSUE TITLE
When unhiding a container, duplicate tabs created

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/testpilot-containers#821] opened 2017-09-15 18:05 UTC
In Firefox 57 using addon- 
1. Open a Work container; go to bugzilla.
2. Open a work container go to google.
3. Hide the Container.
4. Show the Container.

Expected result: two work tabs open, one with bugzilla nd one with google.

Actual result: 4 work tabs open.  First bugzilla, then google, then bugzilla again, then google again.

**Comment by jonathanKingston** [comment] 2017-09-15 19:28
What version of the extension are you using? This I think has been fixed in the latest 4.0.3 at least, which I'm not sure if it's been released.

**Comment by TheLastProject** [comment] 2017-09-16 17:22
Can confirm this behaviour on 4.0.1, which is currently the latest released version for Firefox 55.0.3. Also, what issue is this issue a duplicate of? Having a link to the duplicate would be very helpful.

**Comment by groovecoder** [comment] 2017-09-17 12:30
Dupe of https://github.com/mozilla/testpilot-containers/issues/791. Should be fixed in 4.0.3 when it's reviewed an approved by AMO team.

**Closed by groovecoder** 2017-09-17 12:30 UTC
Labels: bug, duplicate
