### ISSUE TITLE
Popup Menu: A weird thing that is happening 

### ISSUE THREAD

**Issue by duvjones** [mozilla/testpilot-containers#527] opened 2017-05-23 12:56 UTC
Hi, I am not sure if this is a bug or not, so I am going to share my little bit of testing and see if I have something.
And for discourse sake:
Fedora 25, Linux kernel 4.10.15, Firefox 53.0 (64-bit)
I have tired this under wayland and X11

So I am working with containers at the moment, when I noticed some weird. Any time that I right click and link and use it or open a link to a container, the popup menu on the web-page seems to fail to function. 
I cleaned out and disabled my functioning add-on's and still have this behaviour occur, so I toyed with a test profile just to see if a clean install would produce the same effect, and it doesn't.
So while going about regular usage, I make a backup of my bookmarks. After doing that, the popup menu on any web page seems to operate again as normal (until the next time). 

I am a little lost here as to what is happening, so maybe I am onto something. Maybe not. 
If I am not, please help.
If I am.... I really wonder what is causing this issue to happen?

**Comment by jonathanKingston** [comment] 2017-05-23 13:18
By "popup menu" are you referring to:
1. The right click context menu to access the "Always open in this contaner" or,
2. The main browser action with all containers?

**Comment by duvjones** [comment] 2017-05-23 14:32
Open Link in New Container tab

On Tue, May 23, 2017 at 9:18 AM, Jonathan Kingston <notifications@github.com

**Comment by jonathanKingston** [comment] 2017-05-23 15:16
I think this might be a duplicate of #520 or #423 please reopen if there is an issue.

**Closed by jonathanKingston** 2017-05-23 15:16 UTC
