### ISSUE TITLE
In a contextualized "new tab" panel, ctrl+clicking on a panel does not conserve the current context

### ISSUE THREAD

**Issue by shavounet** [mozilla/testpilot-containers#327] opened 2017-03-03 11:04 UTC
Steps to reproduce: 
- open a new tab with some context
- ctrl+click on one "most viewed" panel 
    - note that the middle-click has the same problem

What happens:
- the new tab has the default context

Expected:
- the new tab should keep the same context

**Comment by groovecoder** [comment] 2017-03-03 18:19
Possible duplicate of https://github.com/mozilla/testpilot-containers/issues/244

**Comment by yhager** [comment] 2017-03-03 19:12
works for me on FF 51.0.1 and containers 1.0.4

**Comment by shavounet** [comment] 2017-03-06 14:23
I have the same versions (under linux), but it does not work. Maybe I wasn't clear enough... here is a snapshot:
![selection_088](https://cloud.githubusercontent.com/assets/2323369/23613693/ca9b87f6-0280-11e7-95ea-1a974e26943c.png)

**Comment by groovecoder** [comment] 2017-03-07 16:43
I was unable to reproduce this in Fx 53 on Mac 10.11.6. (With Cmd+Click)

![testpilot-containers-cmd-click-tab](https://cloud.githubusercontent.com/assets/71928/23667251/dc8219f6-0322-11e7-88e2-09fc4324e732.gif)

**Comment by kjozwiak** [comment] 2017-03-08 07:05
I managed to reproduce the issue on macOS and Win 10, but only on the release channel.

> works for me on FF 51.0.1 and containers 1.0.4

Interesting.. I tried fx51.0.1 and I could reproduce the issue @shavounet reported under macOS 10.12.3 and Win 10 Pro.

There's definitely something going on here... I'll investigate/debug further first thing in the morning and see if I can find the reason why I'm seeing this happening under the release channels (fx52.0, fx51.0.1) while the other channels are not being affected (fx53.0b1, fx54.0a2, fx55.0a1)

**STR being used:**

* remove everything Mozilla/FX related
* install a clean instance using a brand new profile
* install testpilot/containers via https://testpilot.firefox.com/
* open several containers and attempt opening tiles under about:newtab using CTRL/Command + Mouse Click

**macOS 10.12.3 x64:**
* fx52.0, buildid: 20170302120751, changeset: 44d6a57ab554 - **_FAILED_** (reproducible)
* fx53.0b1, buildid: 20170307064827, changeset: 2b89485cf946 - PASSED (not reproducible)
* fx54.0a2, buildid: 20170307070455, changeset: 577083e85267 - PASSED (not reproducible)
* fx55.0a1, buildid: 20170307030205, changeset: b7e42143bbbc - PASSED (not reproducible)

**Win 10 Pro x64:**
* fx52.0, buildid: 20170302120751, changeset: 44d6a57ab554 - **_FAILED_** (reproducible)
* fx53.0b1, buildid: 20170307064827, changeset: 2b89485cf946 - PASSED (not reproducible)
* fx54.0a2, buildid: 20170307070455, changeset: 577083e85267 - PASSED (not reproducible)
* fx55.0a1, buildid: 20170307030205, changeset: b7e42143bbbc - PASSED (not reproducible)

**Comment by shavounet** [comment] 2017-03-08 10:29
I found an other issue that may be related: the "personnal" context is missing while right-clicking in a "personnal" about:newtab

![selection_093](https://cloud.githubusercontent.com/assets/2323369/23700208/6acabce8-03f2-11e7-8201-6b83d76a6016.png)

**Comment by kjozwiak** [comment] 2017-03-23 21:24
I went through mozregression using "--find-fix" and it looks like [Bug#1325014](https://bugzilla.mozilla.org/show_bug.cgi?id=1325014) fixes this issue which landed in fx53. This will explain why it's currently not working under fx52 (current release). This also aligns with the test results that I received earlier which are listed above. I went through it once again and could only reproduce this under fx52. It's working correctly under fx53, fx54 and fx55.

Results from mozregression:

 5:58.98 INFO: First good revision: c00506e039838edc821cbf1f8b904d391e4cd346
 5:58.98 INFO: Last bad revision: b4e876cfcd849281493e4fa1f71789a010b6700d
 5:58.98 INFO: Pushlog:
https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=b4e876cfcd849281493e4fa1f71789a010b6700d&tochange=c00506e039838edc821cbf1f8b904d391e4cd346

> I found an other issue that may be related: the "personnal" context is missing while right-clicking in a "personnal" about:newtab

This behaviour is expected. If you right click on a link/thumbnail in a specific container, that specific container should appear at the top of the context menu and not under the "Open Link in New Container Tab" submenu. I've attached an example below. You'll notice that "Open Link in New Personal Tab" is appearing at the top of the context menu and not under the "Open Link in New Container Tab" submenu. @shavounet, if you're seeing something different, please open a new bug.

<img width="467" alt="screen shot 2017-03-23 at 5 05 03 pm" src="https://cloud.githubusercontent.com/assets/2602313/24270355/33578822-0feb-11e7-85ab-45e173a64a08.png">

@groovecoder, @jonathanKingston, I'm going to close this off as it's going to be fixed in the next version so I'm not sure if it's worth the effort.. If you feel differently, please re-open :)

**Closed by kjozwiak** 2017-03-23 21:24 UTC
Labels: bug

**Comment by shavounet** [comment] 2017-03-24 07:01
The patch you're mentioning seems indeed to fix the main issue. To be tested in the next release ;-)

> I found an other issue that may be related: the "personnal" context is missing while right-clicking in a "personnal" about:newtab

About that, as you can see in my screenshot, the 1st option of contextual menu was "Open in a new tab" and not "Open in a new personal tab" ; that was the bug. But it seems fixed in Firefox 52 (see #400).

**Comment by jonathanKingston** [comment] 2017-03-24 15:24
Confirmed on irc but wanted to say here too... it seems fine to wait for the next release on this as it is lower in priority and it should be just over two weeks anyway.

@shavounet your mention of the missing link is odd, glad it is fixed however :)

**Comment by shavounet** [comment] 2018-09-13 15:10
Hello there,

Since Firefox 61, this bug seems to appear again (with the exact same original test case).
Do you want me to fill another issue ?

Thanks

**Comment by chuhta** [comment] 2018-12-03 21:04
I have this issue with Firefox Multi-Account Containers as well on Firefox 63.0.3. I tried this out with a fresh profile and just the one add-on, but I still had the same problem. This is also on Ubuntu 18.04, though I don't know that it makes a difference.

I attached a screen recording of the issue to perhaps help show the nuances if it's not platform or version specific.

![middle-click-container-issue](https://user-images.githubusercontent.com/6410162/49401281-5571f500-f70c-11e8-8339-d73d88e50033.gif)
