### ISSUE TITLE
Sometimes containers lose cookies

### ISSUE THREAD

**Issue by SoniEx2** [mozilla/testpilot-containers#460] opened 2017-04-24 16:01 UTC
## My environment

I have 2 containers: the default non-container, tumblr, and facebook.

I have one tumblr account open on the default non-container, and another open on the tumblr container. I also have 1 facebook tab open.

The tumblr container has 4 tabs, 1 being the dashboard, the rest of them being blogs. The default non-container has many tabs, some of them being blogs, and one of them being the dashboard.

I also have one pinned tab, TweetDeck.

This is all in the same window.

The tumblr container has one dash (`-`) in the name, while the facebook container does not. Both containers are lowercase-letters-only otherwise.

I have uBlock Origin, Greasemonkey, NoScript, Test Pilot, Containers, and WebSocket Monitor enabled. User Scripts are Reek Anti-Adblock Killer. I can give you the rest of my configs if you need them.

If there's anything else you might need, feel free to ask.

## Description of the issue

If I restart my browser, the tumblr container loses its cookies.

**Comment by jonathanKingston** [comment] 2017-05-01 22:06
I think this is a dupe of this: https://github.com/mozilla/testpilot-containers/issues/397

**Closed** 2017-05-25 23:48 UTC
Labels: bug, needs: Testing
