### ISSUE TITLE
Creating a new tab via Alt+Enter opens in no container

### ISSUE THREAD

**Issue by adambowles** [mozilla/testpilot-containers#480] opened 2017-05-04 16:22 UTC
- Open a tab in a container
- Focus the location bar
- Hit Alt+Enter (Cmd+Enter on macOS)
- Tab is opened with no container context

**Comment by groovecoder** [comment] 2017-05-04 16:55
Dupe of https://github.com/mozilla/testpilot-containers/issues/462

**Comment by groovecoder** [comment] 2017-05-04 16:56
Please upvote and/or comment on https://github.com/mozilla/testpilot-containers/issues/462

**Closed by groovecoder** 2017-05-04 16:55 UTC

**Comment by jwbth** [comment] 2024-03-20 08:01
It seems to me that closing this issue make folks overlook the problem of opening URLs that you *typed* in a preferred container and concentrate on opening tabs *before* typing their URL. And while for the latter, you can at least make a middle click on the "+" button, for the former, there is no method at all.
