### ISSUE TITLE
"new Tab", stay in same container?

### ISSUE THREAD

**Issue by puggan** [mozilla/testpilot-containers#342] opened 2017-03-06 12:23 UTC
when pressing the keybinding for a new tab, I get a tab in the default container, instead of the current container.

Reproduce:
1. Open a link in one of your container
2. Press the keybinding for new tab (ctrl+t, meta+t)

Expected:
1. A new tab opens in the current container.

Current:
1. A new tab opens in the default/no container.

**Comment by pklanka** [comment] 2017-03-06 14:50
+1

**Comment by kjozwiak** [comment] 2017-03-30 22:12
I'll leave this opened for now as its in the [top 10](https://github.com/mozilla/testpilot-containers/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) of most up voted feature requests. We've talked about adding shortcuts to the "+" button several times.. Example: [Bug#1245262](https://bugzilla.mozilla.org/show_bug.cgi?id=1245262) and #119.

**Comment by groovecoder** [comment] 2017-06-27 18:59
This sounds like a dupe of https://github.com/mozilla/testpilot-containers/issues/462 ... please add 👍 and/or comments there.

**Closed by groovecoder** 2017-06-27 18:59 UTC
Labels: enhancement, needs: Product
