### ISSUE TITLE
Default home page per container

### ISSUE THREAD

**Issue by jeremiahlee** [mozilla/testpilot-containers#495] opened 2017-05-10 18:07 UTC
I have been using containers to segment certain types of Web apps that I use. For example, I now use my email service, Github, various Twitter accounts, and Google each in their own container. It's fantastic isolation. Please add the ability to have a default home page unique to each container. This would save me time, as I would no longer have to open a new container tab, then go to my destination.

The "always open in this container" feature in the context menu is helpful, but not for use cases where I have multiple accounts for a single service. For example, I manage three different Twitter accounts and have put each account in its own container.

**Comment by jonathanKingston** [comment] 2017-05-12 21:52
This seems like a duplicate of #375 please let me know if it is not.

Glad you are liking containers and assignment!

Thanks!

**Closed by jonathanKingston** 2017-05-12 21:52 UTC
Labels: enhancement
