### ISSUE TITLE
containers "auto-update" did reset my config and all my containers tabs were closed

### ISSUE THREAD

**Issue by gilgamezh** [mozilla/testpilot-containers#388] opened 2017-03-16 17:26 UTC
It happened just now. I was working and all my tabs were closed. (except for the ones without a container).
When I click in the "containers" button i got the default containers settings. (so I lost my custom config)

```
14:20:35 |  ~  firefox --version
Mozilla Firefox 51.0.1
14:23:51 |  ~  uname -a
Linux trantor 4.10.1-1-ARCH #1 SMP PREEMPT Sun Feb 26 21:08:53 UTC 2017 x86_64 GNU/Linux
```
`Build identifier: Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0`
![image](https://cloud.githubusercontent.com/assets/1496486/24009711/93e5134a-0a54-11e7-8f74-983ea79e5de2.png)

What data can I send to you for debug?

**Comment by groovecoder** [comment] 2017-03-16 17:46
Sorry, this was a known bug with the 1.0.4 and 1.1.1 upgrade code. 😢

https://discourse.mozilla-community.org/t/2-0-0-release/14433/2

It's fixed for 2.0.0+ upgrades, so any custom containers you make in 2.0 will stick around during future upgrades.

Closing as dupe of #346, #373, #374.

**Comment by ruihildt** [comment] 2017-03-16 17:46
It was expected between 1.x branch and 2.x branch, see #374.

Dev said it won't happen anymore in the future.

**Closed** 2017-03-16 17:46 UTC

**Comment by gilgamezh** [comment] 2017-03-16 18:10
@groovecoder thanks!
