### ISSUE TITLE
Move tab to Container

### ISSUE THREAD

**Issue by maverick74** [mozilla/testpilot-containers#329] opened 2017-03-03 11:44 UTC
Would be good to be able to right-click an already open tab and be able to move it to a specific container

**Comment by groovecoder** [comment] 2017-03-03 13:09
Closing as dupe of https://github.com/mozilla/testpilot-containers/issues/311 - can you upvote & comment there?

**Closed by groovecoder** 2017-03-03 13:09 UTC

**Comment by maverick74** [comment] 2017-03-03 16:54
sorry, was in a bit of hurry and miss-looked it
