### ISSUE TITLE
Focus is not set, if clicking on the "+" (new tab button) while Firefox is not focused 

### ISSUE THREAD

**Issue by shavounet** [mozilla/testpilot-containers#401] opened 2017-03-22 10:20 UTC
Test case:
- Firefox 52, Containers 2.0
- Unfocus Firefox by having a small window in front of it
- Click on the new tab button ("+")
- Start typing text

Expected
- The text should be entered in the URL bar (as if I wanted to start a new search)

Actual
- The text is entered in this other small window (Firefox has not the focus)

**Comment by jonathanKingston** [comment] 2017-03-24 17:21
This seems like a duplicate of #362 please reopen if it isn't.

**Closed by jonathanKingston** 2017-03-24 17:21 UTC
Labels: duplicate
