### ISSUE TITLE
Custom container with shopping cart missing from the URL bar on creation

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/testpilot-containers#410] opened 2017-04-03 13:49 UTC
STR:
1. Create a new custom container with the shopping cart icon
2. Create a new tab with this new container (using the browser action or + icon)

Notice how the URL bar has the raw icon in the inspector rather than `data-identity-icon="cart"`. Changing from one tab to another fixes the issue.

![selection_533](https://cloud.githubusercontent.com/assets/338988/24612204/7dd718b0-187c-11e7-9cf4-e094b2f9e79d.png)

I can replicate on 52 and 55 on Linux (have not tried other releases or builds).

@bakulf said he would try and replicate this.

**Comment by bakulf** [comment] 2017-04-03 14:13
@kjozwiak are you able to reproduce it? I'm not.

**Comment by jonathanKingston** [comment] 2017-04-03 14:25
This was on my assignment branch however that really shouldn't impact this.

**Comment by kjozwiak** [comment] 2017-04-03 15:30
@bakulf, I've managed to reproduce this using @jonathanKingston latest `auto-container-origin` branch on `jonathanKingston/testpilot-containers`. Because we're merging the `auto-container-origin` branch into master and releasing this feature today, this should be fixed as well.. Moving into the sprint.

STR:

* pull `jonathanKingston/testpilot-containers`
* cd into the `testpilot-containers` directory and `git checkout auto-container-origin branch`
* `npm install` and than `jpm xpi`
* install an unbranded version of fx if you're testing under fx52 via http://archive.mozilla.org/pub/firefox/tinderbox-builds/
* under `about:config`, change `xpinstall.signatures.required;false`
* use the STR that @jonathanKingston mentioned above

**Closed** 2017-04-03 16:17 UTC
Labels: bug
