### ISSUE TITLE
Change Firefox container of already opened tab with page

### ISSUE THREAD

**Issue by MurzNN** [mozilla/testpilot-containers#326] opened 2017-03-03 09:38 UTC
Very often needs to change container of already opened page in tab, without opening new tab and copy-paste url to it. Please give ability to quickly switch container of current already opened tab with page.

Good interface solution for switch container of already opened tab you can see in Multifox extension.

**Comment by groovecoder** [comment] 2017-03-03 13:03
Closing as dupe of #311 - please upvote & comment there.

**Closed by groovecoder** 2017-03-03 13:03 UTC
