### ISSUE TITLE
removing the experiment leaves leftovers in the UI

### ISSUE THREAD

**Issue by kodabb** [mozilla/testpilot-containers#545] opened 2017-05-28 01:55 UTC
After uninstalling this addon, I can still see the container submenu when I right-click a link
I can provide a screenshot if it helps

**Comment by jonathanKingston** [comment] 2017-05-28 10:13
This is a duplicate of #534, if you could leave more info there that would be super helpful.

- Screenshots
- OS Name/Version
- Firefox version
- Addon info from about:support

Thanks!

**Closed by jonathanKingston** 2017-05-28 10:13 UTC
Labels: bug, duplicate
