### ISSUE TITLE
Uninstalling add-on doesn't remove colored underlines on tabs

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot-containers#171] opened 2017-02-10 20:33 UTC
Installed the 0.0.2 add-on from AMO and then created a few random tabs.
Then I went into about:addons and uninstalled the add-on but noticed that the containered tabs don't remove their underlines.

![add-ons_manager_and_reddit__the_front_page_of_the_internet_and_manage_version_0_0_2____containers_experiment____add-ons_for_firefox](https://cloud.githubusercontent.com/assets/557895/22843119/e10095c4-ef8c-11e6-99be-49b790f0a620.png)

**Comment by kjozwiak** [comment] 2017-02-10 22:41
I think this might be related to bug #173. Disabling the Container XPI via about:addons doesn't actually pref off the feature in it's entirely.. The feature is technically still enabled, which might be why the UI hasn't been removed from the tabs.

**Comment by bakulf** [comment] 2017-02-13 14:34
Duplicate of #173. Covered by PR #175

**Closed by bakulf** 2017-02-13 14:34 UTC
