### ISSUE TITLE
Switch container on a tab

### ISSUE THREAD

**Issue by D219** [mozilla/testpilot-containers#377] opened 2017-03-14 09:08 UTC
It happen that I open a tab in a no container context, and want to reload it in a container.
Currently, I have to copy the url, open a new tab in the right container, and paste the url.
Wouldn't it be better to have a way to switch the container that contain a specific tab?

That could be added as a pop up list in the adress bar, in addition of the indicator which show the name and icon of the current container.

**Comment by groovecoder** [comment] 2017-03-14 13:30
This sounds like a duplicate of https://github.com/mozilla/testpilot-containers/issues/311 ? If so, please add a 👍 and comment there.

**Comment by jonathanKingston** [comment] 2017-03-16 04:27
Closing this as seems to be a duplicate of #311. Feel free to comment there or reopen if there is some distinction here etc. Thanks for the report!

**Closed by jonathanKingston** 2017-03-16 04:27 UTC
