### ISSUE TITLE
Test Addon with FF 52 and report breakage

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/testpilot-containers#116] opened 2017-01-26 18:44 UTC
52 goes to release March 7th, so we should be prepared to update the addon by then with fixes necessary for 52.  Branch code with if 52 then X, if 51 then Y.

**Comment by pdehaan** [comment] 2017-01-27 21:33
Tested on Beta build from https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds on macOS and it seemed to work OK (although the + drop down menu seems to still need some work on master branch).

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/22388332/e29f5792-e494-11e6-886a-99b1701e917b.png)

Not sure if it'd be helpful to sign some builds so we can start testing on official non-unbranded builds.

**Comment by kjozwiak** [comment] 2017-01-28 06:51
@TanviHacks, since it looks like Peter is testing with the 51 build, I'll started using the 52 builds. Should both of us be concentrating on the same build, or should we split our efforts as we currently don't know which version we'll be using for the pilot?

> Not sure if it'd be helpful to sign some builds so we can start testing on official non-unbranded builds.

Agreed with Peter, the faster we get non-unbranded builds, the better :) We definitely don't want to start testing everything with official builds at the last minute.

**Comment by TanviHacks** [comment] 2017-01-28 08:14
The experiment will go out when 51 is on release.  But soon after 52 will
be release, so the add on needs to work with both.  Let's ask engineering
oif we should start testing 52 now, or wait until they've done a few more
bug fixes.

**Comment by TanviHacks** [comment] 2017-02-03 18:31
So far so good.

**Comment by kjozwiak** [comment] 2017-02-03 20:04
Creating a list of issues that I'm going to be tracking that are occurring in fx52... Some of these might be in fx51 as well, but they're easier to reproduce/run into while using fx52.

* #150 - easily reproducible under fx52 compared to fx51

**Comment by groovecoder** [comment] 2017-02-15 22:37
Now that we have #127 #135 #150 filed, I'm closing this. File any new/other fx52 bugs as their own issues.

**Closed by groovecoder** 2017-02-15 22:37 UTC
